[package]
name = "librint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.155"

[profile.release-lto]
debug = true
opt-level = 0
debug-assertions = true
inherits = "release"
lto = true

[[bin]]
name = "h2_two"
path = "grad/h2_two.rs"

[[bin]]
name = "h2o_sto"
path = "grad/h2o_sto3g.rs"

[[bin]]
name = "h2o_def"
path = "grad/h2o_def2svp.rs"