[package]
name = "librint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.155"
faer = "0.19.0"

[profile.dev]
#debug = true
opt-level = 0
debug-assertions = true
lto = "fat"
debug = 0

[profile.release]
lto = "fat"
debug = 0
#rustflags = ["-Z", "autodiff=Enable"]

# [lib]
# crate-type = ["cdylib"]
# name = "rint"

#[[bin]]
#name = "int"
#path = "primal/integral.rs"

#[[bin]]
#name = "dint"
#path = "enzyme/integral.rs"

# [[bin]]
# name = "simple"
# path = "tests/simple.rs"
#
# [[bin]]
# name = "contracted"
# path = "tests/contracted.rs"

[[test]]
name = "ovlp"
path = "checks/overlap.rs"

[[test]]
name = "nuc"
path = "checks/nuclear.rs"

[[test]]
name = "kin"
path = "checks/kinetic.rs"
