[project]
name = "librint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "basis-set-exchange>=0.11",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pyscf>=2.12.1",
    "pyscfad>=0.1.10",
    "pytest>=9.0.2",
    "scipy>=1.15.3",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "pymod" }

[tool.setuptools.packages.find]
where = ["pymod"]

